kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jiva-csi-pvc
  namespace: openebs
spec:
  storageClassName: openebs-jiva-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
